apiVersion: v1
data:
  PORT: "4001"
  REACT_APP_ENDPOINT: http://pokemon-backend-deploy-labproj20.apps.ocp.lab.cloudpak.site
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-26T13:25:13Z"
  name: pokemon-cmap
  namespace: labproj20
  resourceVersion: "80547203"
  uid: 881a814d-c40a-41f7-8001-89b7af69b0f5